[package]
name = "register"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
linkme = { workspace = true }

register-macro = { workspace = true }

[lints]
workspace = true
